# Generated by Django 4.1.5 on 2023-01-18 03:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Sekolah",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("npsn", models.CharField(max_length=10)),
                ("nama", models.CharField(max_length=50)),
                ("email", models.EmailField(blank=True, max_length=100, null=True)),
                ("hp", models.CharField(blank=True, max_length=13, null=True)),
                ("alamat", models.TextField(blank=True, null=True)),
                ("provinsi", models.CharField(max_length=50)),
                ("kabupaten_kota", models.CharField(max_length=50)),
                ("kecamatan", models.CharField(max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[("Swasta", "Swasta"), ("Negeri", "Negeri")],
                        max_length=10,
                    ),
                ),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sekolah_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Sekolah",
                "db_table": "sekolah",
                "ordering": ["-id"],
            },
        ),
    ]
