# Generated by Django 4.1.5 on 2023-01-18 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Siswa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=50)),
                ("email", models.EmailField(blank=True, max_length=100, null=True)),
                ("hp", models.CharField(blank=True, max_length=13, null=True)),
                ("alamat", models.TextField(blank=True, null=True)),
                (
                    "jenis_kelamin",
                    models.CharField(
                        choices=[("L", "Laki-laki"), ("P", "Perempuan")], max_length=1
                    ),
                ),
                ("tempat_lahir", models.CharField(max_length=100)),
                ("tanggal_lahir", models.DateField()),
                ("nisn", models.CharField(max_length=20)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Siswa",
                "db_table": "siswa",
                "ordering": ["-id"],
            },
        ),
    ]
